<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIxy6zof\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIxy6zof/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIxy6zof.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIxy6zof\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerIxy6zof\appDevDebugProjectContainer([
    'container.build_hash' => 'Ixy6zof',
    'container.build_id' => 'bb30d483',
    'container.build_time' => 1563193069,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIxy6zof');
