<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2msud6h\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2msud6h/appProdProjectContainer.php') {
    touch(__DIR__.'/Container2msud6h.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container2msud6h\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container2msud6h\appProdProjectContainer([
    'container.build_hash' => '2msud6h',
    'container.build_id' => '4a586a4b',
    'container.build_time' => 1563127725,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2msud6h');
